### PR TITLE
progress

### PR DESCRIPTION
**Pull request by ReenExe**

### CODE REVIEW

**Comment by ReenExe** [comment]
Giuseppe, something wrong StochasticGradientDescentTest fail - so comment line

**Comment by gburtini** [comment]
I will investigate before merging.

**Comment by ReenExe** [comment]
I found part of code that was write a half? so i move it - how was, without logical change

**Comment by ReenExe** [comment]
some like `sann`
But project have tests, and we thy covers other

**Comment by gburtini** [comment]
There is lots of code in the library which is missing tests right now.  SANN should work, but I do not believe has unit tests.

**Comment by ReenExe** [comment]
I finish move to OOP
Giuseppe we have different timezone (now 23+ in my clock), so continue in friday

**Comment by gburtini** [comment]
13:00 here. I'm on the west coast. Keep up the good work, I will review when you're all done.

Sleep well!

**Comment by ReenExe** [comment]
I finish `SANN` but it very dirty
So you can check tests https://travis-ci.org/ReenExeContributor/Learning-Library-for-PHP/branches

**Comment by gburtini** [comment]
Right, the tests for SANN are currently not PHPUnit. They were written by another author who submitted a PR. 

I don't have time to rewrite them as PHPUnit right now. If you want to, please feel free, it should be relatively straightforward as the code at the bottom that computes $solutionScore should be as close to 0 as possible (check if it is within 0.1 of 0 for now?)

https://github.com/gburtini/Learning-Library-for-PHP/blob/master/tests/sann_test.php

$this->assertEqual(0, $solutionScore, '', 0.1);

Obviously having just the one unit test isn't great. I've personally never actually used this SANN code though.

**Comment by ReenExe** [comment]
$solutionScore between 1 and 29+

2016-02-04 20:22 GMT+02:00 Giuseppe Burtini <notifications@github.com>:

**Comment by ReenExe** [comment]
add commit with changes, answer i will read on Friday (home and so on)

2016-02-04 20:35 GMT+02:00 Ярослав Характерник <ipourri@gmail.com>:

**Comment by gburtini** [comment]
Sorry, I'm slow on this. 

I recommend just commenting out that test for now (and leaving no active tests for SANN) and eventually I will either write a proper test for it or ask the initial author to review it. I don't have time to get deep in to it right now, I know this SANN build has been used in production so it is likely I am just misunderstanding something.

**Comment by gburtini** [comment]
Does this pull request require changes to the tests?

**Comment by ReenExe** [comment]
Yes, but not all tests passed before my changes - so they commented, other passed

**Pull request closed without merging**
